import { AppImage } from '@/components/common/AppImage';
import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Check, ArrowUpRight, Mail, Camera, Globe, Heart } from 'lucide-react';
import { Container, Heading, CTA, DemoNotice } from '@/components/common/Shared';
import { Button } from '@/components/ui/button';
import { FeatureGrid, SolutionGrid, Workflow, FaceFeature, FAQ } from './Sections';
import { plans } from '@/data/pricing';
import { solutions } from '@/data/solutions';
import { images } from '@/data/images';
import { site } from '@/data/site';
export function PageIntro({title,description,eyebrow}:{title:string;description:string;eyebrow:string}) {return <section className="border-b border-border bg-secondary/40 py-16 sm:py-20"><Container className="max-w-4xl text-center"><p className="mb-4 text-xs font-bold uppercase tracking-[0.16em] text-primary">{eyebrow}</p><h1 className="text-4xl font-bold leading-tight sm:text-5xl">{title}</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground">{description}</p></Container></section>;}
export function FeaturesPage() {return <><PageIntro eyebrow="Built around your craft" title="Less admin. More unforgettable." description="A thoughtful toolkit for organizing event photos and helping people find their moments."/><section className="py-20"><Container><FeatureGrid/></Container></section><FaceFeature/><CTA/></>;}
export function HowPage() {return <><PageIntro eyebrow="From shutter to shared" title="Beautifully simple. Start to finish." description="Create an event, bring your photos together, and let every guest discover a personal collection."/><Workflow/><FaceFeature/><CTA/></>;}
export function SolutionsPage() {return <><PageIntro eyebrow="A gallery for every occasion" title="Made for your kind of moment." description="Different crowds. Different stories. One beautifully connected photo experience."/><section className="py-16"><Container><SolutionGrid/></Container></section><CTA/></>;}
export function SolutionPage({slug}:{slug:string}) {const s=solutions.find(x=>x.slug===slug);if(!s)return <Container className="py-20"><h1 className="text-3xl font-bold">Solution not found</h1><Link to="/solutions" className="mt-5 block text-primary">Explore solutions</Link></Container>;return <><section className="relative isolate overflow-hidden"><AppImage src={s.image} width={1920} height={1024} alt={`${s.name} celebration`} className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-overlay/65"/><Container className="py-24 text-ink-foreground"><p className="mb-4 text-sm">Photography solutions</p><h1 className="text-4xl font-bold sm:text-5xl">{s.name} photo galleries</h1><p className="mt-5 max-w-xl text-lg leading-relaxed">{s.description}</p><Button asChild className="mt-8" size="lg"><Link to="/demo-gallery">Explore a sample gallery<ArrowUpRight/></Link></Button></Container></section><section className="py-16"><Container className="grid gap-12 md:grid-cols-2"><Heading eyebrow="The challenge" title="Great photos shouldn't get lost." description={s.problem}/><Heading eyebrow="A better experience" title="Let every guest find their story." description="Bring your collection into a branded event gallery, organize it around the occasion, and prepare personal discovery for your guests."/></Container></section><Workflow/><section className="py-16 bg-muted"><Container><Heading title="Made for the way you work."/><FeatureGrid limit={6}/></Container></section><section className="py-16"><Container><Heading title="A glimpse of the possibilities."/><div className="grid gap-4 sm:grid-cols-3">{[s.image,images.portrait,images.dance].map((src,i)=><AppImage key={i} src={src} alt={`Example event collection ${i+1}`} loading="lazy" width={1024} height={768} className="aspect-[4/3] w-full rounded-lg object-cover"/>)}</div></Container></section><CTA/></>;}
export function PricingPage() {const[annual,setAnnual]=useState(false);return <><PageIntro eyebrow="Room to grow" title="Your craft. Your pace. Your plan." description="From your first gallery to your busiest season, find a plan that feels right."/><section className="py-12"><Container><div className="mb-10 flex justify-center"><div className="inline-flex rounded-lg border border-border bg-muted p-1"><Button variant={annual?'ghost':'default'} onClick={()=>setAnnual(false)}>Monthly</Button><Button variant={annual?'default':'ghost'} onClick={()=>setAnnual(true)}>Annual <span className="text-[10px]">−20%</span></Button></div></div><DemoNotice>Illustrative pricing only · No subscriptions or payments are active.</DemoNotice><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{plans.map(p=><article key={p.name} className={`relative flex flex-col rounded-lg border p-6 ${p.featured?'border-primary bg-secondary/30':'border-border bg-card'}`}>{p.featured&&<span className="absolute -top-3 left-6 rounded-full bg-primary px-3 py-1 text-[10px] font-semibold text-primary-foreground">For growing studios</span>}<h2 className="text-lg font-bold">{p.name}</h2><p className="mt-2 text-xs text-muted-foreground">{p.description}</p><p className="my-6 text-4xl font-bold">${annual?Math.round(p.monthly*.8):p.monthly}<span className="text-sm font-normal text-muted-foreground"> / month</span></p><p className="mb-5 text-xs text-muted-foreground">{annual&&p.monthly?`Demo annual total: $${Math.round(p.monthly*.8)*12}`:'Demo price · USD'}</p><Button variant={p.featured?'default':'outline'} asChild><Link to="/signup">Choose {p.name}<ArrowUpRight/></Link></Button><ul className="mt-7 flex-1 space-y-4">{p.features.map(f=><li key={f} className="flex items-start gap-2 text-xs leading-relaxed"><Check className="size-4 shrink-0 text-success"/>{f}</li>)}</ul></article>)}</div><div className="mt-12 overflow-x-auto"><h2 className="mb-6 text-xl font-bold">At a glance</h2><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-border"><tr><th className="p-4">Included interface</th>{plans.map(p=><th key={p.name} className="p-4">{p.name}</th>)}</tr></thead><tbody>{['Event gallery','Favorites & sharing','Studio branding','Analytics workspace'].map((f,i)=><tr className="border-b border-border" key={f}><th className="p-4 font-medium">{f}</th>{plans.map((p,j)=><td key={p.name} className="p-4">{i<2||j>1?<Check className="size-4 text-success"/>:'—'}</td>)}</tr>)}</tbody></table></div><div className="mt-12 flex flex-wrap items-center justify-between gap-6 border-y border-border py-8"><div><h2 className="text-xl font-bold">A bigger vision?</h2><p className="mt-2 text-sm text-muted-foreground">Let’s talk about your team, your events, and what comes next.</p></div><Button asChild variant="outline"><Link to="/contact">Talk to us<ArrowUpRight/></Link></Button></div></Container></section><FAQ/></>;}
export function AboutPage(){return <><PageIntro eyebrow="Behind the moments" title="Photography connects us." description="We believe the best part of a photo is the person who gets to relive it."/><section className="py-16"><Container className="grid items-center gap-12 md:grid-cols-2"><AppImage src={images.festival} alt="Friends sharing a joyful festival moment" width={1024} height={768} className="aspect-[4/3] rounded-lg object-cover"/><div><Heading title="Every photo has someone waiting for it." description={`${site.fullName} is a vision for a more personal event photography experience. A place where photographers can present their work beautifully, and guests can find the moments that belong to them.`}/><p className="text-sm leading-relaxed text-muted-foreground">We’re designing around the real journey—from busy event days to thoughtful gallery delivery. The current product is a frontend preview of that journey.</p></div></Container></section><section className="bg-muted py-16"><Container className="grid gap-10 md:grid-cols-3">{[[Camera,'Respect the craft','Make room for beautiful work, not endless administration.'],[Heart,'Make it personal','Give people a meaningful way to find their memories.'],[Globe,'Think beyond borders','Design for every celebration, wherever it happens.']].map(([Icon,t,d])=>{const I=Icon as typeof Camera;return <div key={String(t)}><I className="mb-5 text-primary"/><h2 className="mb-3 text-xl font-bold">{String(t)}</h2><p className="text-sm leading-relaxed text-muted-foreground">{String(d)}</p></div>})}</Container></section><CTA/></>;}
