import { AppImage } from '@/components/common/AppImage';
import { Link } from '@tanstack/react-router';
import { CalendarPlus, CloudUpload, ScanFace, Share2, ArrowUpRight, Sparkles, Images, QrCode, ShieldCheck, Smartphone, Heart, Check, Play } from 'lucide-react';
import { Container, Heading } from '@/components/common/Shared';
import { Button } from '@/components/ui/button';
import { steps, features } from '@/data/features';
import { solutions } from '@/data/solutions';
import { faqs } from '@/data/faq';
import { images } from '@/data/images';
const icons=[CalendarPlus,CloudUpload,ScanFace,Share2];
export function Workflow() {return <section className="py-20"><Container><Heading center eyebrow="Simple from the first click" title="From your camera to their memories." description="A smoother workflow for you. A little magic for your guests."/><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{steps.map((s,i)=>{const Icon=icons[i];return <div key={s.title} className="relative"><div className="mb-6 flex items-center gap-4"><span className="flex size-12 items-center justify-center rounded-lg bg-secondary text-primary">{Icon&&<Icon size={22}/>}</span><span className="text-xs text-muted-foreground">0{i+1}</span><span className="h-px flex-1 bg-border"/></div><h3 className="mb-3 text-lg font-semibold">{s.title}</h3><p className="text-sm leading-relaxed text-muted-foreground">{s.description}</p></div>})}</div></Container></section>;}
export function SolutionGrid({limit}:{limit?:number}) {return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{solutions.slice(0,limit).map(s=><Link to="/solutions/$slug" params={{slug:s.slug}} key={s.slug} className="group overflow-hidden rounded-lg border border-border bg-card"><div className="aspect-[1.6] overflow-hidden"><AppImage src={s.image} alt={`${s.name} event photography`} loading="lazy" width={1024} height={768} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/></div><div className="p-5"><div className="flex justify-between"><h3 className="text-lg font-semibold">{s.name}</h3><ArrowUpRight className="size-5 text-muted-foreground"/></div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.description}</p></div></Link>)}</div>;}
export function FeatureGrid({limit}:{limit?:number}) {const iconSet=[ScanFace,Images,QrCode,CloudUpload,Share2,Smartphone,Heart,Sparkles];return <div className="grid gap-x-10 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{features.slice(0,limit).map((f,i)=>{const Icon=iconSet[i%iconSet.length];return <div key={f.name}><span className="mb-5 inline-flex size-11 items-center justify-center rounded-lg bg-secondary text-primary">{Icon&&<Icon size={22}/>}</span><h3 className="mb-2 text-lg font-semibold">{f.name}</h3><p className="text-sm leading-relaxed text-muted-foreground">{f.description}</p></div>})}</div>;}
export function FAQ() {return <section className="py-20"><Container className="max-w-4xl"><Heading center eyebrow="A little more clarity" title="Good questions. Simple answers."/><div className="divide-y divide-border">{faqs.map(f=><details key={f.question} className="group py-5"><summary className="flex list-none items-center justify-between gap-6 font-semibold">{f.question}<span className="text-xl text-primary group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{f.answer}</p></details>)}</div></Container></section>;}
export function FaceFeature() {return <section className="bg-muted py-20"><Container className="grid items-center gap-12 lg:grid-cols-2"><div><p className="mb-4 text-xs font-bold uppercase tracking-[0.15em] text-primary">A selfie. A little magic.</p><h2 className="max-w-md text-3xl font-bold leading-tight sm:text-4xl">Find every photo<br/>you're in.</h2><p className="mt-5 max-w-md text-base leading-relaxed text-muted-foreground">Less scrolling through hundreds of photos. More reliving the moments that are yours. A personal photo discovery experience, made for every guest.</p><ul className="my-7 space-y-3 text-sm">{['One selfie to start your search','Your moments, in one collection','Made for guests on the go'].map(t=><li className="flex items-center gap-3" key={t}><Check className="size-4 text-success"/>{t}</li>)}</ul><Button asChild variant="outline"><Link to="/demo-gallery">Try the photo discovery demo<ArrowUpRight/></Link></Button></div><div className="relative mx-auto w-full max-w-lg rounded-lg border border-border bg-card p-5 shadow-soft"><div className="mb-5 flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-semibold"><ScanFace className="size-5 text-primary"/> Your moments, found</span><span className="rounded-full bg-success-soft px-2 py-1 text-[10px] text-success">Sample matches</span></div><div className="grid grid-cols-3 gap-3">{[images.portrait,images.wedding,images.dance].map((src,i)=><div key={src} className="relative h-48 overflow-hidden rounded-md"><AppImage src={src} alt={['Bride with her friends','Newlyweds in the garden','Couple dancing'][i]} width={300} height={400} loading="lazy" className="h-full w-full object-cover"/><span className="absolute bottom-2 right-2 flex size-5 items-center justify-center rounded-full bg-success text-primary-foreground"><Check size={12}/></span></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-md bg-secondary p-3"><Sparkles className="size-5 text-primary"/><div><p className="text-xs font-semibold">The moments that matter to you.</p><p className="mt-1 text-[10px] text-muted-foreground">Personal photo discovery · Frontend preview</p></div></div></div></Container></section>;}
export function Trust() {return <section className="border-b border-border py-7"><Container><div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-4 text-xs font-medium text-muted-foreground">{[[ShieldCheck,'Thoughtful guest access'],[ScanFace,'AI-powered discovery'],[Images,'Beautiful event galleries'],[Smartphone,'Mobile-first experience']].map(([Icon,text])=>{const I=Icon as typeof ShieldCheck;return <span key={String(text)} className="flex items-center gap-2"><I size={17}/>{String(text)}</span>})}</div></Container></section>;}
