import { AppImage } from '@/components/common/AppImage';
import { useEffect, useState } from 'react';
import { ScanFace, Upload, Check, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { images } from '@/data/images';
export function FaceSearch({open,onClose,onResults}:{open:boolean;onClose:()=>void;onResults:()=>void}) {
 const[selfie,setSelfie]=useState('');const[consent,setConsent]=useState(false);const[state,setState]=useState<'choose'|'searching'|'found'>('choose');const[error,setError]=useState('');
 useEffect(()=>{if(state!=='searching')return;const timer=setTimeout(()=>setState('found'),1800);return()=>clearTimeout(timer)},[state]);
 useEffect(()=>()=>{if(selfie.startsWith('blob:'))URL.revokeObjectURL(selfie)},[selfie]);
 // BACKEND TODO: Send consented face image to search API; receive matching IDs and confidence metadata.
 return <Dialog open={open} onOpenChange={v=>{if(!v){onClose();setState('choose')}}}><DialogContent className="w-[94vw] max-w-md"><DialogTitle className="flex items-center gap-2"><ScanFace className="text-primary"/>Find your moments</DialogTitle><DialogDescription>Photo discovery preview · No facial recognition is performed.</DialogDescription>{state==='choose'?<><label className="flex min-h-48 cursor-pointer flex-col items-center justify-center gap-3 rounded-lg border-2 border-dashed border-border bg-muted p-5">{selfie?<AppImage src={selfie} alt="Selected selfie preview" className="size-28 rounded-full object-cover"/>:<Upload className="size-8 text-primary"/>}<span className="text-sm font-semibold">{selfie?'Choose a different selfie':'Choose your selfie'}</span><span className="text-xs text-muted-foreground">JPEG, PNG, WebP · Up to 10 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024){setError('Choose a supported image under 10 MB.');return;}setSelfie(URL.createObjectURL(f));setError('')}}/></label><Button variant="ghost" onClick={()=>setSelfie(images.portrait)}>Use example selfie instead</Button>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<label className="flex items-start gap-3 text-xs leading-relaxed"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I understand this local preview displays sample matches and does not upload my selfie.</label><Button disabled={!selfie||!consent} onClick={()=>setState('searching')}>Find my photos<ScanFace/></Button></>:state==='searching'?<div className="py-10 text-center" role="status"><div className="relative mx-auto size-32 overflow-hidden rounded-full border-4 border-primary"><AppImage src={selfie} alt="Selfie preview" className="h-full w-full object-cover"/><div className="absolute inset-0 animate-pulse bg-primary/15"/></div><LoaderCircle className="mx-auto mt-6 animate-spin text-primary"/><p className="mt-4 font-semibold">Searching your event...</p><p className="mt-2 text-xs text-muted-foreground">Simulated photo discovery</p></div>:<div className="py-4 text-center" role="status"><Check className="mx-auto mb-4 size-10 rounded-full bg-success-soft p-2 text-success"/><h3 className="text-xl font-bold">Your sample matches are ready.</h3><div className="my-5 grid grid-cols-3 gap-2">{[images.portrait,images.wedding,images.dance].map(src=><AppImage key={src} src={src} alt="Example photo match" width={200} height={250} className="h-32 w-full rounded object-cover"/>)}</div><p className="mb-5 text-xs text-muted-foreground">These are predefined demo results, not actual face matches.</p><Button className="w-full" onClick={()=>{onResults();onClose();setState('choose')}}>View my sample photos</Button></div>}</DialogContent></Dialog>;
}
