import { useState } from 'react';
import { Heart, Download, Share2, ChevronLeft, ChevronRight, ZoomIn, ZoomOut, Check, Maximize } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import type { Photo } from '@/types/common';
import { toast } from 'sonner';
export async function shareLink() {try{await navigator.clipboard.writeText(window.location.href);toast.success('Gallery link copied.');}catch{toast.error('Copy is unavailable in this browser.');}}
export async function downloadDemo(photo:Photo) {
 // BACKEND TODO: Request a secure signed photo download URL.
 try {const response=await fetch(photo.src);if(!response.ok)throw new Error('Download unavailable');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${photo.title.toLowerCase().replaceAll(' ','-')}.jpg`;a.click();URL.revokeObjectURL(url);toast.success('Demo photo downloaded.');}catch{toast.error('Could not download this demo photo.');}
}
export function PhotoViewer({photos,index,onClose,onChange,favorites,onFavorite,selected,onSelect}:{photos:Photo[];index:number|null;onClose:()=>void;onChange:(i:number)=>void;favorites:Set<string>;onFavorite:(id:string)=>void;selected:Set<string>;onSelect:(id:string)=>void}) {
 const[zoom,setZoom]=useState(false);const photo=index===null?undefined:photos[index];
 return <Dialog open={!!photo} onOpenChange={v=>{if(!v){setZoom(false);onClose();}}}><DialogContent className="max-h-[95dvh] w-[95vw] max-w-6xl overflow-y-auto p-4 sm:p-6">{photo&&<><DialogTitle className="pr-9">{photo.title}</DialogTitle><DialogDescription>Morgan Studio · {photo.category} · September 20, 2026</DialogDescription><div className="relative flex h-[48dvh] items-center justify-center overflow-auto rounded-md bg-ink sm:h-[60dvh]" onKeyDown={e=>{if(index===null)return;if(e.key==='ArrowRight'){setZoom(false);onChange((index+1)%photos.length)}if(e.key==='ArrowLeft'){setZoom(false);onChange((index-1+photos.length)%photos.length)}} tabIndex={0} aria-label="Photo viewer. Use arrow keys to browse."><img src={photo.src} alt={photo.title} width={photo.width} height={photo.height} className={zoom?'h-auto w-[150%] max-w-none shrink-0':'h-full w-full object-contain'}/><Button variant="secondary" size="icon" className="absolute left-2 top-1/2" aria-label="Previous photo" onClick={()=>{if(index!==null)onChange((index-1+photos.length)%photos.length);setZoom(false)}}><ChevronLeft/></Button><Button variant="secondary" size="icon" className="absolute right-2 top-1/2" aria-label="Next photo" onClick={()=>{if(index!==null)onChange((index+1)%photos.length);setZoom(false)}}><ChevronRight/></Button></div><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{(index??0)+1} / {photos.length} · Original demo image</span><div className="flex flex-wrap gap-2"><Button variant={favorites.has(photo.id)?'default':'outline'} size="icon" title="Favorite" aria-label="Favorite photo" onClick={()=>onFavorite(photo.id)}><Heart/></Button><Button variant={selected.has(photo.id)?'default':'outline'} size="icon" title="Select" aria-label="Select photo" onClick={()=>onSelect(photo.id)}><Check/></Button><Button variant="outline" size="icon" title="Share" aria-label="Share photo" onClick={shareLink}><Share2/></Button><Button variant="outline" size="icon" title="Download demo photo" aria-label="Download photo" onClick={()=>downloadDemo(photo)}><Download/></Button><Button variant="outline" size="icon" title={zoom?'Zoom out':'Zoom in'} aria-label={zoom?'Zoom out':'Zoom in'} onClick={()=>setZoom(!zoom)}>{zoom?<ZoomOut/>:<ZoomIn/>}</Button><Button variant="outline" size="icon" title="Fullscreen" aria-label="Fullscreen photo" onClick={()=>{const el=document.querySelector('[aria-label="Photo viewer. Use arrow keys to browse."]');el?.requestFullscreen?.().catch(()=>toast.error('Fullscreen is unavailable.'));}}><Maximize/></Button></div></div></>}</DialogContent></Dialog>;
}
