import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Aperture, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { site } from '@/data/site';
import type { ReactNode } from 'react';
export function Brand() { return <Link to="/" className="inline-flex shrink-0 items-center gap-2.5 font-bold text-xl"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Aperture size={25}/></span>{site.brandName}<span className="rounded border border-border px-1.5 py-0.5 text-[10px] font-semibold text-muted-foreground">{site.brandSuffix}</span></Link>; }
export function Container({children,className=''}:{children:ReactNode;className?:string}) { return <div className={`mx-auto w-full max-w-7xl px-5 sm:px-8 lg:px-12 ${className}`}>{children}</div>; }
export function Heading({eyebrow,title,description,center=false}:{eyebrow?:string;title:string;description?:string;center?:boolean}) { return <div className={`mb-10 ${center?'mx-auto max-w-2xl text-center':''}`}>{eyebrow&&<p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-primary">{eyebrow}</p>}<h2 className="text-3xl font-bold leading-tight sm:text-4xl">{title}</h2>{description&&<p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">{description}</p>}</div>; }
export function CTA() {return <section className="bg-secondary py-16"><Container className="flex flex-col items-center justify-between gap-8 text-center md:flex-row md:text-left"><div><p className="mb-3 flex items-center justify-center gap-2 text-primary md:justify-start"><Sparkles size={16}/> More memories. Less searching.</p><h2 className="text-3xl font-bold">Your next event deserves this.</h2><p className="mt-3 text-muted-foreground">Create a beautiful home for every photo and every guest.</p></div><Button asChild size="lg"><Link to="/signup">{site.cta.primary}<ArrowUpRight/></Link></Button></Container></section>;}
export function DemoNotice({children='Demo workspace · Changes stay in this session.'}:{children?:ReactNode}) {return <p className="rounded-md border border-border bg-secondary px-4 py-2 text-xs text-muted-foreground">{children}</p>;}
